### ISSUE TITLE
crop and align doesn't work

### ISSUE THREAD

**Issue by monajalal** [cleardusk/EmotionChallenge#2]
So, I get this error for Python 3:

```
[jalal@goku cnn]$ python extract.py
Traceback (most recent call last):
  File "extract.py", line 78, in <module>

▽
    submit()
  File "extract.py", line 74, in submit
    extract('../models/final.caffemodel')
  File "extract.py", line 61, in extract
    pred = classifier.predict(img, landmark)
  File "extract.py", line 32, in predict
    self.net.blobs['data'].data[0, ...] = image_array.transpose((2, 0, 1))

▽
AttributeError: 'NoneType' object has no attribute 'transpose'
```

Looking at the code:
```
def extract(model_file):
    classifier = Classifier(model_file=model_file,
                            deploy_file='deploy.prototxt')
    records = open('../data/test_ld.txt').read().strip().split('\n')
    # print(records[:1])
    predicts = []
    for rec in records:
        rec = rec.split()
        fp = rec[0]
        # print(fp)
        landmark = rec[1:]
        landmark = map(float, landmark)
        # print(landmark)
        assert len(list(landmark)) == 136
```

It is looking at this file:
../data/test_ld.txt

Looking at this file:
I have something like 
../data/face_224/104/Sample_104_001.JPG
I expect to see a folder named 104 in the face_224 folder. However, there is no folder here and only a readme.md file which says `224x224 size image stores here.`
```
[jalal@goku data]$ cd face_224/
[jalal@goku face_224]$ ls
readme.md
```

So I am confused what has gone wrong and how to fix it?
Any suggestion is really appreciated. I had no problem with the first step which was done in  the crop_align folder:
```
[jalal@goku crop_align]$ python landmark.py
[jalal@goku crop_align]$
```
From what I understand the crop didn't work because you are stating that you expect the cropped folder to be in data/face_224 folder in which face_224 is the name of my image however, there's nothing in that folder.

Any help is really appreciated.

**Comment by cleardusk** [comment]
For example, the row below in `../data/test_ld.txt` records one image path and 68x2=136 landmarks. The image are after cropping and alignment to size 224x224. You should crop and align the source images to this directory `../data/face_224` or modify it with a minor code change. Note that, the images of each identity are put into one directory named with id number such as `104`, and it need you to complete it (just several lines of  python code).
```
../data/face_224/104/Sample_104_001.JPG -5.436001 -21.244003 -4.307999 -19.543999 -2.764000 -18.947998 -1.251999 -19.755997 0.543999 -20.492004 1.587997 -19.919998 1.071999 -19.259995 -0.468002 -16.776001 -1.987999 -16.227997 -3.975998 -16.339996 -6.335999 -18.800003 -9.595993 -20.363998 -11.195999 -21.496002 -10.507996 -20.584000 -9.884003 -19.535995 -8.147995 -19.099998 -6.503998 -18.148003 -4.380001 -7.536003 -0.183998 -2.264000 0.879997 3.939999 1.000000 6.596001 0.571999 5.475998 -1.487999 8.391998 -1.856003 10.388000 -2.988007 9.816002 -4.007996 5.784000 -1.576004 0.068001 0.080002 0.260002 0.515999 2.816002 1.227997 5.431999 2.124001 8.491997 -0.863998 -0.908005 -0.848000 0.776001 -0.867996 1.815994 -0.900002 0.916000 -0.888000 0.496002 -3.472000 -10.036003 -2.384003 -6.084000 -2.695999 -4.580002 -4.339996 -4.811996 -4.391998 -5.699997 -4.204002 -7.139999 -0.363998 -2.851997 -1.052002 -0.204002 -2.044006 0.036003 -1.895996 -2.828003 -1.776001 -1.512001 -0.755997 -2.416000 -2.211998 -8.076004 -0.047997 -2.104004 -0.092003 0.020004 -1.031998 0.112000 -1.300003 0.815994 -3.488007 -0.608002 -5.371994 -4.164001 -5.108002 -4.292007 -2.388000 -5.951996 -1.484001 -6.423996 -1.947998 -6.511993 -0.412003 -6.975998 -2.435997 -6.531998 -1.375999 -2.016006 -1.396004 -1.492004 -1.872002 -1.259995 -5.923996 -3.563995 -1.688004 -5.067993 -1.199997 -5.371994 -1.115997 -6.492004
```
